apiVersion: v2
name: n8n-clone
description: A Helm chart for N8N Clone microservices architecture
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - workflow
  - automation
  - microservices
  - n8n
home: https://github.com/your-org/n8n-clone
sources:
  - https://github.com/your-org/n8n-clone
maintainers:
  - name: N8N Clone Team
    email: team@n8n-clone.com
dependencies:
  - name: postgresql
    version: 12.x.x
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: redis
    version: 17.x.x
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
  - name: kafka
    version: 22.x.x
    repository: https://charts.bitnami.com/bitnami
    condition: kafka.enabled
